

struct CpuIn = {
    clk :: Bit;
    reset :: Bit;
    int_ext :: Bit;
    from_host :: Bits (8);
    read_data :: Bits (32);
    inst :: Bits (32);
}

struct CpuOut = {
    tohost :: Bits (8);
    addr :: Bits (8);
    wen :: Bit;
    write_data :: Bits (32);
    iaddr :: Bits (32);
}




interface MIPSCPU = 
    set_clk :: Bits (1) -> Action
    input :: 

mkCPU = module


interface ArithIO a =
    input :: a -> a -> Action
    output :: a

mkGCD :: Module (ArithIO (Bit 32))
mkGCD = module
    x :: Reg (Bit 32)
    x <- mkReg _

    y :: Reg (Bit 32)
    y <- mkReg _
    
    done :: Reg Bool
    done <- mkReg True
    
    interface
        input a b = action { x._write a; y._write b; done._write False } when done._read
        output = x._read when done._read
    
    rules
        when not done._read, x._read > y._read, y._read /= 0
            ==> action { x._write y; y._write x }
        when not done._read, y._read == 0
            ==> action { done._write True }
        when not done._read, x._read <= y._read, y._read /= 0
            ==> action { y._write (y._read - x._read) }